[package]
name = "bird-protocol-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1.0.47"

[dependencies.syn]
version = "1.0.103"
features = ["full"]

[dependencies.quote]
version = "1.0.21"
